version: '3'
services:
  php-apache:
    build: . 
    image: php7.3-apache
    ports: 
      - 80:80
    volumes: 
      - $PWD:/var/www/html
    links: 
      - mysql
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=master
      - MYSQL_DATABASE=devkaize_wp243
      - MYSQL_USER=devkaize_wp243
      - MYSQL_PASSWORD=p1SAB9].O6
